version: '2.4'
services:
  Server1:
    container_name: E4GLStatusBot_Server1
    build:
      context: .
    image: registry.gitlab.com/e4gl/bf4statusbot:latest
    userns_mode: "host"
    restart: unless-stopped
    environment:
      BF4STATUSBOT_BOT_TOKEN: ""
      BF4STATUSBOT_SERVER_GUID: ""
      # the following variables are optional
      # BF4STATUSBOT_CHECK_MAP: "True"
      # BF4STATUSBOT_INTERVAL_PRESENCE_CHANGE: "5"
      # BF4STATUSBOT_INTERVAL_DATA_FETCH: "20"

    # volumes:
    #   - type: bind
    #     source: ./server1.toml
    #     target: /usr/src/app/config/user.toml
    security_opt:
      - no-new-privileges
    mem_limit: 500M
    mem_reservation: 250M

  # create an own service for each server
  Server2:
    container_name: E4GLStatusBot_Server2
    image: registry.gitlab.com/e4gl/bf4statusbot:latest
    userns_mode: "host"
    restart: unless-stopped
    environment:
      BF4STATUSBOT_BOT_TOKEN: ""
      BF4STATUSBOT_SERVER_GUID: ""
    security_opt:
      - no-new-privileges
    mem_limit: 500M
    mem_reservation: 250M

  Server3:
    container_name: E4GLStatusBot_Server3
    image: registry.gitlab.com/e4gl/bf4statusbot:latest
    userns_mode: "host"
    restart: unless-stopped
    environment:
      BF4STATUSBOT_BOT_TOKEN: ""
      BF4STATUSBOT_SERVER_GUID: ""
    security_opt:
      - no-new-privileges
    mem_limit: 500M
    mem_reservation: 250M
